# file = open('file2.txt', 'r')
# data = file.read()
# print(data)
# data = file.read(50)
# print(data)
# data = file.readline()
# print(data)
# data = file.readline()
# print(data)
# data = file.readline()
# print(data)
# data = file.readline()
# print(data)
# data = file.readline()
# print(data)
# data = file.readlines()
# print(data)


file = open("file3.txt", 'a')
file.write("\nI'm writing for the fourth time")